# Generated by Django 5.2.4 on 2025-07-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('image', models.ImageField(blank=True, default='cv_person_img/default.jpg', null=True, upload_to='cv_person_img/')),
                ('summary', models.TextField()),
                ('address', models.TextField()),
                ('education', models.TextField()),
                ('certifications', models.TextField()),
                ('projects', models.TextField()),
                ('experience', models.TextField()),
                ('skills', models.TextField(choices=[('Basic', 'Basic'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Basic', max_length=50)),
            ],
            options={
                'verbose_name': 'CV',
                'verbose_name_plural': 'CVs',
            },
        ),
    ]
