# Generated by Django 5.2.4 on 2025-07-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_app_1', '0002_alter_cv_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='image',
            field=models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='images/'),
        ),
    ]
