# Generated by Django 5.2.4 on 2025-07-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_app_1', '0003_alter_cv_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='image',
            field=models.ImageField(blank=True, default='media/images/default.jpg', null=True, upload_to='images/'),
        ),
    ]
